#!/bin/sh
#
# Contain Environment variables for installs
#

HOME_DIR="/home/vagrant"

SHARED_DIR="/vagrant"

DOWNLOAD_DIR="$SHARED_DIR/downloads"
if [ ! -d $DOWNLOAD_DIR ]; then
  mkdir $DOWNLOAD_DIR
fi

FEDORA_VERSION=4.3.1-SNAPSHOT
FEDORA_TAG=4.3.1-SNAPSHOT
# true to enable auth, false to disable it
FEDORA_AUTH=false
FEDORA_AUDIT=true
FEDORA_AUDIT_LOCATION=/audit
FEDORA_DATA=/var/lib/tomcat7/fcrepo4-data


FUSEKI_VERSION=2.3.0
FUSEKI_BASE=/etc/fuseki
FUSEKI_DEPLOY=/var/lib/tomcat7/webapps

TOMCAT_LOGS=/var/lib/tomcat7
TOMCAT_LIBS=/usr/share/tomcat7/lib/
WEBAPPS_DIR=/var/lib/tomcat7/webapps
TOMCAT_CONF=/etc/tomcat7

SOLR_VERSION=4.10.3
SOLR_HOME=/var/lib/tomcat7/solr

KARAF_VERSION=4.0.1
KARAF_DIR=/opt

TOMCAT_USER=tomcat7
TOMCAT_GROUP=tomcat7

TOMCAT_CONTROLLER="service tomcat7"
TOMCAT_ENV=/etc/default/tomcat7

JAVA8_HOME=/usr/lib/jvm/java-8-oracle
