#!/bin/sh
#
# Contain Environment variables for installs
#

HOME_DIR="/home/vagrant"

SHARED_DIR="/vagrant"

DOWNLOAD_DIR="$SHARED_DIR/downloads"
if [ ! -d $DOWNLOAD_DIR ]; then
  mkdir $DOWNLOAD_DIR
fi

FEDORA_VERSION=4.3.1-SNAPSHOT
FEDORA_TAG=4.3.1-SNAPSHOT
# true to enable auth, false to disable it
FEDORA_AUTH=false
FEDORA_AUDIT=true
FEDORA_AUDIT_LOCATION=/audit
FEDORA_DATA=/var/lib/tomcat8/fcrepo4-data


FUSEKI_VERSION=2.3.0
FUSEKI_BASE=/etc/fuseki
FUSEKI_DEPLOY=/var/lib/tomcat8/webapps

TOMCAT_LOGS=/var/lib/tomcat8
TOMCAT_LIBS=/usr/share/tomcat8/lib/
WEBAPPS_DIR=/var/lib/tomcat8/webapps
TOMCAT_CONF=/etc/tomcat8

SOLR_VERSION=4.10.3
SOLR_HOME=/var/lib/tomcat8/solr

KARAF_VERSION=4.0.1
KARAF_DIR=/opt

TOMCAT_USER=tomcat8
TOMCAT_GROUP=tomcat8

TOMCAT_CONTROLLER="service tomcat8"
TOMCAT_ENV=/etc/default/tomcat8

JAVA8_HOME=/usr/lib/jvm/java-8-oracle

#SERVICED=YES